# This file is generated by gyp; do not edit.

export builddir_name ?= /home/frankfang/Downloads/gyp/gyp-read-only/test/copies/src/out
.PHONY: all
all:
	$(MAKE) copies1 copies_null copies_recursive_depth copies_recursive copies2
